# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@32332eee51c01b3804b256223e7a5358828284fd # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@32332eee51c01b3804b256223e7a5358828284fd # develop
