# SPDX-FileCopyrightText: Copyright © 2024 - 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: license
on: [push, workflow_call]
jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - run: uv run --frozen --group dev reuse lint
