# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: node-cli
on: [push, workflow_call]
jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: corepack enable
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn exec git-conventional-commits --version
      - run: yarn exec lint-staged --version
