# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: node-cli
on: [push, workflow_call]
jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: asdf-vm/actions/plugins-add@v4.0.1
      - run: asdf install nodejs
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn exec git-conventional-commits --version
      - run: yarn exec lint-staged --version
