# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@62692ab8e49d81be34499565efd304df809a6ebb # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@62692ab8e49d81be34499565efd304df809a6ebb # develop
