# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@701368ce1cf5392951e0af9f591bed9169b3239f # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@701368ce1cf5392951e0af9f591bed9169b3239f # develop
