# SPDX-FileCopyrightText: Copyright © 2024, 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: prettier
on: [push, workflow_call]
jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: corepack enable
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: "yarn"
      - run: yarn install --immutable --inline-builds --check-resolutions
      - run: yarn exec prettier --ignore-unknown --check '**'
