# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: test
on: [push]
jobs:
  yarn:
    uses: xenoterracide/github/.github/workflows/yarn.yml@8c5fe0f3eb42d9eb5e0d110929cbefd0f8670f86 # develop
