# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: test
on: [push]
jobs:
  yarn:
    uses: xenoterracide/github/.github/workflows/yarn.yml@32332eee51c01b3804b256223e7a5358828284fd # develop
